/*
 *  DO NOT EDIT THIS FILE -- IT WAS GENERATED WITH makever
 */

char version[] = "\
Ini file configuration utility\n\
Version 1.4 as of Fri Mar 23 14:30:37 CET 2012.\n\
Compiled for Darwin 11.3.0\n\
Copyright (C) 1998-2012 OpenLink Software.\n";
