/*
 *  DO NOT EDIT THIS FILE -- IT WAS GENERATED WITH makever
 */

char version[] = "\
Ini file configuration utility\n\
Version 1.4 as of Tue Mar 29 22:10:47 CEST 2011.\n\
Compiled for Linux 2.6.27.56-0.1-default\n\
Copyright (C) OpenLink Software.\n";
