/* This file is automatically generated by plugin/gen_gate.sh */
#include <stdlib.h>
#include "import_plugin_msdtc.h"
struct _gate_s _gate = {
  { NULL, "dbg_calloc" },
  { NULL, "dbg_free" },
  { NULL, "dbg_malloc" },
  { NULL, "dbg_malloc_enable" },
  { NULL, "dbg_realloc" },
  { NULL, "dbg_strdup" },
  { NULL, "." } };
