/*
 *  DO NOT EDIT THIS FILE -- IT WAS GENERATED WITH makever
 */

char version[] = "\
OpenLink Virtuoso ODBC Driver (multi threaded)\n\
Version 06.01.3127 as of Mon Oct 31 18:10:40 CET 2011.\n\
Compiled for Linux 2.6.37.1-1.2-default\n\
Copyright (C) OpenLink Software.\n";
