/*
 *  DO NOT EDIT THIS FILE -- IT WAS GENERATED WITH makever
 */

char version[] = "\
OpenLink Virtuoso ODBC Driver (Unicode)\n\
Version 06.01.3127 as of Thu Aug  2 00:16:37 CEST 2012.\n\
Compiled for Darwin 11.4.0\n\
Copyright (C) 1998-2012 OpenLink Software.\n";
