/*
 *  DO NOT EDIT THIS FILE -- IT WAS GENERATED WITH makever
 */

char version[] = "\
OpenLink ODBC Mail Interface\n\
Version 2.01 as of Fri Oct 28 19:31:13 CEST 2011.\n\
Compiled for Linux 2.6.37.1-1.2-default\n\
Copyright (C) OpenLink Software.\n";
