/*
 *  DO NOT EDIT THIS FILE -- IT WAS GENERATED WITH makever
 */

char version[] = "\
OpenLink Virtuoso Mail Interface\n\
Version 2.01 as of Wed Aug  1 18:07:31 CEST 2012.\n\
Compiled for Darwin 11.4.0\n\
Copyright (C) 1998-2012 OpenLink Software.\n";
